### ISSUE TITLE
楼主好久没有更新了啊,有想过支持语音消息和语音通话和视频通话吗?

### ISSUE THREAD

**Issue by hehaipeng** [itsonglin/wechat_desktop#1]
楼主好久没有更新了啊,有想过支持语音消息和语音通话和视频通话吗?

**Comment by itsonglin** [comment]
哈哈,我还以为没什么人关注这个呢...语音消息可以考虑试试..不过最近发现swing在Window平台下的表现远不如mac, 正在考虑用C#重写windows客户端呢..

**Comment by hehaipeng** [comment]
我看了你的代码设计非常好，完全实现了新的android思维，swing开发windows应用确实存在许多不便之处.
期待你的C#版更新...有机会我可以参加集成后台功能进去。



pax1122@163.com
 
发件人： songlin.zhong
发送时间： 2017-12-13 08:33
收件人： itsonglin/wechat_desktop
抄送： hehaipeng; Author
主题： Re: [itsonglin/wechat_desktop] 楼主好久没有更新了啊,有想过支持语音消息和语音通话和视频通话吗? (#1)
哈哈,我还以为没什么人关注这个呢...语音消息可以考虑试试..不过最近发现swing在Window平台下的表现远不如mac, 正在考虑用C#重写windows客户端呢..

**Comment by 24Kzs** [comment]
为啥我的数据库生成不了
