### ISSUE TITLE
内存泄漏问题

### ISSUE THREAD

**Issue by youonly-once** [itsonglin/wechat_desktop#12]
截屏完成后ScreenShot没有dispose

**Comment by itsonglin** [comment]
谢谢你指出问题.
具体是哪个地方没有dispose呢?
如果是指ScreenShotFrame的话, 在[close](https://github.com/itsonglin/wechat_desktop/blob/2.0/src/com/rc/frames/ScreenShotFrame.java#L1044)方法里面是有调用dispose方法的, 可以再去看看
