### ISSUE TITLE
请问有测试用的账号和密码吗？需要配置服务器吗？

### ISSUE THREAD

**Issue by willenigma** [itsonglin/wechat_desktop#2]
想学着写一个类似的，想先让程序跑起来看一看。编译可以成功，有登录窗口，但是没有账号，没办法登录成功。请问可以告知一下吗？

**Comment by itsonglin** [comment]
不好意思最近工作比较忙, 没时间回复.

**Comment by itsonglin** [comment]
这个只是一个客户端程序, 无需搭建服务器的, 如果你想自己搭建一个在线聊天服务器, 可以试Rocket.Chat: https://rocket.chat/download. Rocket.Chat提供了丰富的restful和Websocket api. 我记得登录窗口的用户名密码校验逻辑已经注释了, 直接点击登录按钮即可进入主界面.

**Comment by lky-95** [comment]
为什么我这直接点击登录按钮，提示请输入用户

**Comment by itsonglin** [comment]
用户名密码校验逻辑是注释起来的, 你检查一下LoginFrame.java是不是把注释打开了.

**Comment by windskyl** [comment]
如果直接点击登录按钮，会不显示界面，直接退出程序，请问这是为什么呢。
请问这个项目的运行环境是什么呢，有一些组件报错
环境：
win10，jdk10
IntelliJ IDEA 2018.2 (Community Edition)
