### ISSUE TITLE
为什么，不能及时聊天，怎么解决，开始的时候，自动生成不了数据库，求解决...

### ISSUE THREAD

**Issue by 24Kzs** [itsonglin/wechat_desktop#3]

**Comment by 24Kzs** [comment]
怎么生成数据库

**Comment by itsonglin** [comment]
有什么错误提示吗, 检查一下sqlite的驱动包有没有导入.

**Comment by 24Kzs** [comment]
导入了

**Comment by 24Kzs** [comment]
我把ide变成了eclpse，是不是哪里文件错误了，系统可以正常运行，就是数据库生成不了

**Comment by itsonglin** [comment]
数据库会自动载入根目录下的wechat.db的.另外, 你要把res目录设置成资源目录, 如果是用Intellij的话, 对着src目录右键 - make directory as resources root即可, eclipse不清楚怎么设置.
