### ISSUE TITLE
搭建起来报错

### ISSUE THREAD

**Issue by lcxiaoma** [itsonglin/wechat_desktop#4]
我的java1.9  运行的时候提示找不到类
Error:(4, 32) java: 程序包com.sun.image.codec.jpeg不存在
Error:(7, 15) java: 程序包 org.omg.PortableInterceptor 不可见
  (程序包 org.omg.PortableInterceptor 已在模块 java.corba 中声明, 但该模块不在模块图中)
Error:(4, 20) java: 程序包com.rc.forms不存在
等等 
这是怎么回事

**Comment by itsonglin** [comment]
应该是没有指定源代码目录, 如果是用Intellij, 对src目录右键 - make directory as resources root

**Comment by itsonglin** [comment]
应该是没有指定源代码目录, 如果是用Intellij, 对src目录右键 - make directory as resources root

**Comment by windskyl** [comment]
并没有用，而且似乎您上传的包少了org文件夹以及里面所有的东西，导致错误

**Comment by itsonglin** [comment]
在idea中,对lib目录右键 -> add as library, 对src目录右键 -> Mark Directory as -> sources root
