### ISSUE TITLE
大神，你好！我们现在是在用您的开源代码写一个IM 项目，可否留个邮箱，有问题想请教下

### ISSUE THREAD

**Issue by 18575652880** [itsonglin/wechat_desktop#7]
我的邮箱839977417@qq.com

**Comment by itsonglin** [comment]
有什么疑问就在这里提出来吧, 大家可以一起讨论.

**Comment by 18575652880** [comment]
嗯，好的。比如跟好友聊天，好友消息回显到聊天界面您是怎么做的，还有这个项目好像不能创建群聊，望解答谢谢

**Comment by itsonglin** [comment]
> 嗯，好的。比如跟好友聊天，好友消息回显到聊天界面您是怎么做的，还有这个项目好像不能创建群聊，望解答谢谢

只是实现了UI, 创建群聊需要连服务器
